# Generated by Django 4.2.1 on 2023-06-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
